// <auto-generated />
using System;
using Infrastructure.Presistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(TravelDBContext))]
    [Migration("20250308093352_AddedInquiryStatusColumn")]
    partial class AddedInquiryStatusColumn
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CustomerId"));

                    b.Property<string>("EmailAddress")
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PreferredContactMethod")
                        .HasColumnType("text");

                    b.Property<string>("PreferredTimeForContact")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("CustomerId");

                    b.ToTable("Customer");
                });

            modelBuilder.Entity("Domain.Entities.CustomerPreferences", b =>
                {
                    b.Property<int>("CustomerPreferencesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CustomerPreferencesId"));

                    b.Property<int>("CustomerId")
                        .HasColumnType("integer");

                    b.Property<bool>("GuidedTours")
                        .HasColumnType("boolean");

                    b.Property<string>("PackageInclusions")
                        .HasColumnType("text");

                    b.Property<string>("PreferredTourDuration")
                        .HasColumnType("text");

                    b.HasKey("CustomerPreferencesId");

                    b.HasIndex("CustomerId")
                        .IsUnique();

                    b.ToTable("CustomerPreferences");
                });

            modelBuilder.Entity("Domain.Entities.OtherInformation", b =>
                {
                    b.Property<int>("OtherInformationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("OtherInformationId"));

                    b.Property<int>("CustomerId")
                        .HasColumnType("integer");

                    b.Property<string>("HowDidYouHearAboutUs")
                        .HasColumnType("text");

                    b.Property<bool>("PreviousCustomer")
                        .HasColumnType("boolean");

                    b.HasKey("OtherInformationId");

                    b.HasIndex("CustomerId")
                        .IsUnique();

                    b.ToTable("OtherInformation");
                });

            modelBuilder.Entity("Domain.Entities.PackagePreference", b =>
                {
                    b.Property<int>("PackagePreferenceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PackagePreferenceId"));

                    b.Property<string>("AccommodationType")
                        .HasColumnType("text");

                    b.Property<decimal?>("BudgetRange")
                        .HasColumnType("numeric");

                    b.Property<int>("CustomerId")
                        .HasColumnType("integer");

                    b.Property<string>("MealPreferences")
                        .HasColumnType("text");

                    b.Property<string>("PackageType")
                        .HasColumnType("text");

                    b.Property<string>("PreferredActivities")
                        .HasColumnType("text");

                    b.Property<string>("TransportationPreference")
                        .HasColumnType("text");

                    b.HasKey("PackagePreferenceId");

                    b.HasIndex("CustomerId")
                        .IsUnique();

                    b.ToTable("PackagePreferences");
                });

            modelBuilder.Entity("Domain.Entities.SpecialRequirements", b =>
                {
                    b.Property<int>("SpecialRequirementsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SpecialRequirementsId"));

                    b.Property<int>("CustomerId")
                        .HasColumnType("integer");

                    b.Property<string>("SpecialRequests")
                        .HasColumnType("text");

                    b.Property<bool>("TravelInsurance")
                        .HasColumnType("boolean");

                    b.HasKey("SpecialRequirementsId");

                    b.HasIndex("CustomerId")
                        .IsUnique();

                    b.ToTable("SpecialRequirements");
                });

            modelBuilder.Entity("Domain.Entities.TravelDetails", b =>
                {
                    b.Property<int>("TravelDetailsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TravelDetailsId"));

                    b.Property<int>("CustomerId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("FlexibleDates")
                        .HasColumnType("boolean");

                    b.Property<int?>("NumberOfAdults")
                        .HasColumnType("integer");

                    b.Property<int?>("NumberOfChildren")
                        .HasColumnType("integer");

                    b.Property<int?>("NumberOfInfants")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TravelDestination")
                        .HasColumnType("text");

                    b.Property<string>("TravelPurpose")
                        .HasColumnType("text");

                    b.HasKey("TravelDetailsId");

                    b.HasIndex("CustomerId")
                        .IsUnique();

                    b.ToTable("TravelDetails");
                });

            modelBuilder.Entity("Domain.Entities.CustomerPreferences", b =>
                {
                    b.HasOne("Domain.Entities.Customer", "Customer")
                        .WithOne("CustomerPreferences")
                        .HasForeignKey("Domain.Entities.CustomerPreferences", "CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("Domain.Entities.OtherInformation", b =>
                {
                    b.HasOne("Domain.Entities.Customer", "Customer")
                        .WithOne("OtherInformation")
                        .HasForeignKey("Domain.Entities.OtherInformation", "CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("Domain.Entities.PackagePreference", b =>
                {
                    b.HasOne("Domain.Entities.Customer", "Customer")
                        .WithOne("PackagePreference")
                        .HasForeignKey("Domain.Entities.PackagePreference", "CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("Domain.Entities.SpecialRequirements", b =>
                {
                    b.HasOne("Domain.Entities.Customer", "Customer")
                        .WithOne("SpecialRequirements")
                        .HasForeignKey("Domain.Entities.SpecialRequirements", "CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("Domain.Entities.TravelDetails", b =>
                {
                    b.HasOne("Domain.Entities.Customer", "Customer")
                        .WithOne("TravelDetails")
                        .HasForeignKey("Domain.Entities.TravelDetails", "CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("Domain.Entities.Customer", b =>
                {
                    b.Navigation("CustomerPreferences")
                        .IsRequired();

                    b.Navigation("OtherInformation")
                        .IsRequired();

                    b.Navigation("PackagePreference")
                        .IsRequired();

                    b.Navigation("SpecialRequirements")
                        .IsRequired();

                    b.Navigation("TravelDetails")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
